# Generated by Django 5.1.6 on 2025-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('expertise_area', models.CharField(choices=[('technology', 'Technology & Programming'), ('business', 'Business & Finance'), ('design', 'Design & Creative'), ('marketing', 'Marketing & Sales'), ('health', 'Health & Fitness'), ('language', 'Language Learning'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'db_table': 'Instructor_restr',
            },
        ),
    ]
