# Generated by Django 5.1.6 on 2025-07-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=100),
            preserve_default=False,
        ),
    ]
