# Generated by Django 5.1.6 on 2025-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('lessons', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
