# Generated by Django 5.1.6 on 2025-03-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_courses_id_alter_lesson_id_alter_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='instructor',
        ),
    ]
