# Generated by Django 5.1.6 on 2025-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
