# Generated by Django 5.1.6 on 2025-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
