# Generated by Django 5.1.6 on 2025-03-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='lesson',
            field=models.IntegerField(default=0),
        ),
    ]
