# Generated by Django 5.1.6 on 2025-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
